Account, Block, Mempool, Network API Services
LimeChain/hedera-mirror-node pull request #149
Opened 2020-10-14 14:01 UTC by georgiyazovaliiski

** Changes **
Unit tests for Data API
Account Service
Block Service
Mempool Service
Network Service

2020-10-14 15:12 UTC, failfmi commented on hedera-mirror-rosetta/app/services/network_service_test.go
> +	networkService := NewNetworkAPIService(
You can extract `NewNetworkAPIService` initialization into a helper function.

2020-10-14 15:45 UTC, failfmi commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	accountService := NewAccountAPIService(commons, mocks.MAccountRepository)
Good idea should be to add a scenario, which tests `NewAccountAPIService` - asserts correct return type
```go
assert.IsType(t, &AccountAPIService{}, accountService)
```
and its fields if possible.

2020-10-14 15:54 UTC, failfmi commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	accountService := NewAccountAPIService(commons, mocks.MAccountRepository)
The same applies for `NewBlockAPIService`, `NewMempoolAPIService` and `NewNetworkAPIService`.

2020-10-16 08:05 UTC, Daniel-K-Ivanov requested changes

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	assert.IsType(t, &AccountAPIService{}, accountService)
I think that it would be good to test the populated properties as-well, f.e:
```Go
assert.Equal(t, commons, accountService.Commons, "Commons was not populated correctly")
assert.Equal(t, mocks.MAccountRepository, accountService.accountRepo, "AccountsRepository was not populated correctly")
```

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	}
nit: for the sake of blockchain terminology, let's make the parnet index equal to the Index - 1 => 0

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	exampleBlock := &types.Block{
we could extract this code to a function:
```Go
func block() *types.Block {
	return &types.Block{
		Index:               1,
		Hash:                "0x123jsjs",
		ConsensusStartNanos: 1000000,
		ConsensusEndNanos:   20000000,
		ParentIndex:         2,
		ParentHash:          "0xparenthash",
	}
}
```
and reuse it in `TestAccountBalance`, `TestAccountBalanceFullData` and `TestAccountBalanceThrowsWhenRetrieveBalanceAtBlockFails`

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	expectedAccountBalanceResponse := &rTypes.AccountBalanceResponse{
we could extract this code to a function:
```Go
func expectedAccountBalanceResponse() *rTypes.AccountBalanceResponse {
	return &rTypes.AccountBalanceResponse{
		BlockIdentifier: &rTypes.BlockIdentifier{
			Index: 1,
			Hash:  "0x123jsjs",
		},
		Balances: []*rTypes.Amount{
			{
				Value:    "1000",
				Currency: config.CurrencyHbar,
			},
		},
	}
}
```
and reuse it in `TestAccountBalance` and `TestAccountBalanceFullData`

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	accountService := NewAccountAPIService(commons, mocks.MAccountRepository)
As those 2 lines are used in every test, you can extract function and do:
```Go
accountService := getSubject()
```
and 
```Go
func getSubject() *AccountAPIService {
	commons := NewCommons(mocks.MBlockRepository, mocks.MTransactionRepository)
	return NewAccountAPIService(commons, mocks.MAccountRepository)
}
```

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	assert.Nil(t, e)
You could assert that `FindByIdentifier` or `FindByHash` was not called similar to the next test

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +func TestAccountBalanceFullData(t *testing.T) {
I think that `TestAccountBalanceWithBlockIdentifier` is a better name for the test.

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	exampleBlock := &types.Block{
I think that we could even remove the `0x`es for hash and parent hash. This way we will check that we are safely adding `0x` in te response

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	assert.NotNil(t, e)
I think that it would be better to check that the error type is correct, not only that its not nill

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +func TestAccountBalanceThrows(t *testing.T) {
- We could add another test that checks that when `RetrieveBlock` returns an error, we are returning that error, similar to this test but for `FindByIdentifier`
- I think that `TestAccountBalanceThrowsWhenRetrieveLatestFails` is a better name for the test + we would have `TestAccountBalanceThrowsWhenRetrieveBlockFails` test as-well :)

2020-10-16 08:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	assert.Nil(t, actualResult)
We could add assert that `RetrieveBalanceAtBlock` was never called

2020-10-16 10:13 UTC, georgiyazovaliiski commented on hedera-mirror-rosetta/app/services/account_service_test.go
> +	assert.IsType(t, &AccountAPIService{}, accountService)
This is only possible to do in Account Service.
Other services either return specific Servicer types (which only expose certain methods and encapsulate everything else) or do not have fields to be checked.

2020-10-16 12:45 UTC, Daniel-K-Ivanov requested changes

2020-10-16 12:45 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/account/account_service_test.go
> +	repository.MBlockRepository.On("RetrieveLatest").Return(block(), repository.NilError)
This is not required in this test

2020-10-16 12:45 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/block/block_service_test.go
> +	assert.NotNil(t, e)
I think that everytime where you check that the error is of type Error you are implicitly checking that error is not nil, meaning that if you have:
```Go
assert.IsType(t, &rTypes.Error{}, e)
```
you have a implicit check:

```Go
assert.NotNil(t, e)
```

2020-10-16 12:45 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/block/block_service_test.go
> +func TestBlockTransaction(t *testing.T) {
I think that a meaningful check would be that hex.SafeRemoveHexPrefix was called once with the request.BlockIdentifier.Hash as parameter

2020-10-16 12:45 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/network/network_service_test.go
> +	networkService := networkAPIService(baseService)
Isn't this `getSubject` function?

2020-10-16 12:45 UTC, Daniel-K-Ivanov commented on hedera-mirror-rosetta/app/services/network/network_service_test.go
> +func TestNetworkOptions(t *testing.T) {
I think that you should add 2 tests where:
-  `TypesAsArray` returns error
- `Statuses` returns error
as they are not covered at the moment

2020-10-16 13:40 UTC, Daniel-K-Ivanov approved these changes

2020-10-16 13:43 UTC, merged