Rosetta pguser addition
LimeChain/hedera-mirror-node pull request #162
Opened 2020-10-28 08:19 UTC by georgiyazovaliiski

2020-10-28 12:05 UTC, Daniel-K-Ivanov requested changes
Suggestion: add "if not exist" in the statements for the user creation

2020-10-28 12:05 UTC, Daniel-K-Ivanov commented on hedera-mirror-importer/src/main/resources/db/scripts/init.sql
> +create user :rosetta_user with login password :'mirror_rosetta_pass';
I think that this should be `rosetta_password` not `mirror_rosetta_pass`

2020-10-28 12:46 UTC, failfmi commented
Target branch is a bit old, please fork [hashgraph:rosetta](https://github.com/hashgraph/hedera-mirror-node/tree/rosetta) and switch to it.

2020-11-04 13:55 UTC, failfmi commented on docs/installation.md
> +database schema. The SQL script located at `hedera-mirror-importer/src/main/resources/db/scripts/0_init.sql` can be used to
The SQL scripts located at `hedera-mirror-importer/src/main/resources/db/scripts/init` can be used to...

2020-11-04 13:55 UTC, failfmi commented on docs/installation.md
>  `grpc_password` as appropriate.
`rosetta_user`, or `rosetta_password` as appropriate.

2020-11-04 13:55 UTC, failfmi commented on docs/installation.md
> +psql postgres -f hedera-mirror-importer/src/main/resources/db/scripts/0_init.sql
```
psql postgres -f hedera-mirror-importer/src/main/resources/db/scripts/init/0_init.sql
psql postgres -f hedera-mirror-importer/src/main/resources/db/scripts/init/1_grants.sql
```
or a way to execute the `init` directory as a whole

2020-11-04 13:55 UTC, failfmi commented on hedera-mirror-importer/src/main/resources/db/scripts/init/0_init.sql
> +  create user mirror_node with SUPERUSER password 'mirror_node_pass';
Not everything here uses the variables above

2020-11-04 15:48 UTC, failfmi approved these changes

2020-11-05 10:14 UTC, failfmi approved these changes

2020-11-05 11:14 UTC, Daniel-K-Ivanov approved these changes

2020-11-05 13:04 UTC, merged